### ISSUE TITLE
"You are not permitted to access this resource" while viewing pull request with non-admin user

### ISSUE THREAD

**Issue by mobikop** [pbaranchikov/stash-eol-check#3]
c.a.s.i.h.r.RepositoryMergeRequestCheckAdapter Merge Check com.pbaranchikov.stash-eol-check:stash-check-eol-hook failed.
com.atlassian.stash.exception.AuthorisationException: You are not permitted to access this resource
    at com.atlassian.stash.internal.aop.ExceptionRewriteAdvice.afterThrowing(ExceptionRewriteAdvice.java:36) ~[stash-platform-3.11.2.jar:na]
    at com.pbaranchikov.stash.checks.EolCheckHook.getChangeSet(EolCheckHook.java:127) ~[na:na]
    at com.pbaranchikov.stash.checks.EolCheckHook.check(EolCheckHook.java:91) ~[na:na]
    at com.atlassian.stash.internal.hook.repository.RepositoryMergeRequestCheckAdapter$1.visit(RepositoryMergeRequestCheckAdapter.java:35) [stash-service-impl-3.11.2.jar:na]
    at com.atlassian.stash.internal.hook.repository.RepositoryMergeRequestCheckAdapter$1.visit(RepositoryMergeRequestCheckAdapter.java:31) [stash-service-impl-3.11.2.jar:na]
    at com.atlassian.stash.internal.hook.repository.DefaultRepositoryHookService$RepositoryHookPagedTransactionCallback.doInTransaction(DefaultRepositoryHookService.java:611) [stash-service-impl-3.11.2.jar:na]
    at com.atlassian.stash.internal.hook.repository.DefaultRepositoryHookService$RepositoryHookPagedTransactionCallback.doInTransaction(DefaultRepositoryHookService.java:587) [stash-service-impl-3.11.2.jar:na]
    at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133) [spring-tx-4.1.6.RELEASE.jar:4.1.6.RELEASE]
    at com.atlassian.stash.internal.hook.repository.DefaultRepositoryHookService.visitEnabledHooks(DefaultRepositoryHookService.java:304) [stash-service-impl-3.11.2.jar:na]
    at com.atlassian.stash.internal.plugin.OsgiSafeProxyProvider$1.invoke(OsgiSafeProxyProvider.java:93) [stash-platform-3.11.2.jar:na]
    at com.atlassian.stash.internal.hook.repository.RepositoryMergeRequestCheckAdapter.check(RepositoryMergeRequestCheckAdapter.java:31) [stash-service-impl-3.11.2.jar:na]
    at com.atlassian.stash.internal.pull.DefaultMergeRequestCheckService.doCheck(DefaultMergeRequestCheckService.java:73) [stash-service-impl-3.11.2.jar:na]
    at com.atlassian.stash.internal.pull.DefaultMergeRequestCheckService.checkMergeability(DefaultMergeRequestCheckService.java:57) [stash-service-impl-3.11.2.jar:na]
    at com.atlassian.stash.internal.pull.DefaultPullRequestService.canMerge(DefaultPullRequestService.java:365) [stash-service-impl-3.11.2.jar:na]
    at com.atlassian.stash.internal.rest.pull.PullRequestResource.canMerge(PullRequestResource.java:431) [stash-rest-3.11.2.jar:na]
    at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:25) [applinks-plugin-4.3.7_1436971150000.jar:na]
    at com.atlassian.stash.internal.spring.security.StashAuthenticationFilter.doFilter(StashAuthenticationFilter.java:88) [StashAuthenticationFilter.class:na]
    at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doInsideSpringSecurityChain(BeforeLoginPluginAuthenticationFilter.java:109) [BeforeLoginPluginAuthenticationFilter.class:na]
    at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doFilter(BeforeLoginPluginAuthenticationFilter.java:75) [BeforeLoginPluginAuthenticationFilter.class:na]
    at com.atlassian.security.auth.trustedapps.filter.TrustedApplicationsFilter.doFilter(TrustedApplicationsFilter.java:103) [atlassian-trusted-apps-core-4.0.0.jar:na]
    at com.atlassian.oauth.serviceprovider.internal.servlet.OAuthFilter.doFilter(OAuthFilter.java:79) [atlassian-oauth-service-provider-plugin-1.9.10_1438150930000.jar:na]
    at com.atlassian.analytics.client.filter.DefaultAnalyticsFilter.doFilter(DefaultAnalyticsFilter.java:36) [analytics-client-3.70.1_1436161294000.jar:na]
    at com.atlassian.analytics.client.filter.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:32) [analytics-client-3.70.1_1436161294000.jar:na]
    at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doBeforeBeforeLoginFilters(BeforeLoginPluginAuthenticationFilter.java:87) [BeforeLoginPluginAuthenticationFilter.class:na]
    at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doFilter(BeforeLoginPluginAuthenticationFilter.java:73) [BeforeLoginPluginAuthenticationFilter.class:na]
    at com.atlassian.stash.internal.request.DefaultRequestManager.doAsRequest(DefaultRequestManager.java:85) [stash-service-impl-3.11.2.jar:na]
    at com.atlassian.stash.internal.hazelcast.ConfigurableWebFilter.doFilter(ConfigurableWebFilter.java:38) [ConfigurableWebFilter.class:na]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_40]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_40]
    ... 352 frames trimmed
Caused by: org.springframework.security.access.AccessDeniedException: Access is denied
    at org.springframework.security.access.vote.AffirmativeBased.decide(AffirmativeBased.java:83) ~[spring-security-core-3.2.7.RELEASE.jar:3.2.7.RELEASE]
    ... 29 common frames omitted

**Comment by pbaranchikov** [comment]
@mobikop, could you please explain, what you did, what are the security restrictions. I.e. describe how to reproduce the issue.

**Comment by mobikop** [comment]
When I create PR from fork repo to main I get that stacktrace in the atlassian-stash.log. It could if you trying to get access to atlassian services in created threas. The following code could help:

service.execute(new Runnable() {
                    @Override
                    public void run() {
                        EscalatedSecurityContext context = securityService.
                                impersonating(pullRequest.getAuthor().getUser(), "Update reviewers");
                        context.call(new Operation<Object, RuntimeException>() {
                            @Override
                            public Object perform() throws RuntimeException {
                                //do some work
                                return null;
                            }
                        });
                    }
                });
